### ISSUE TITLE
getCombatLevel doesn't take into account skill max of 99

### ISSUE THREAD

**Issue by ehardisty** [darrenswhite/IronQuest#1]
My combat level is reported at 147.0. This is due to the formula calculating from virtual skill levels not for real skill levels.

The effect of this shouldn't be too commonly observed, but it is possible this would flag some quests as meeting the requirements, and thus optimal complete when they're not. (e.g. a level 98 player with 120 defence would be shown as over 100 combat, so The World Wakes may be suggested as the best quest to complete, when the player wont really be able to complete it)

![Screenshot of my RS account + info loaded into Quest Planner application](http://i.imgur.com/yRmX1d8.jpg)

**Comment by ehardisty** [comment]
After taking the image, I've noticed it's calculated my quest points incorrectly. I'll try to find out why.

**Comment by darrenswhite** [comment]
I'll look into fixing the combat level calculation this weekend. I initially thought of blacklisting "Unstable Foundations" but noticed that it was needed in some cases (unless I have a quest with a missing quest point somewhere 👎).

**Comment by darrenswhite** [comment]
@ehardisty would you be able to build & test the devel branch and confirm if it is still a problem.

**Comment by ehardisty** [comment]
I'll check it out when I get home tonight.

**Comment by ehardisty** [comment]
Combat calc is fixed. It took me a while to setup as you haven't got google GSON or apache commons-csv in your POM file, and I had to modify `FILE_QUESTS_JSON` in `IronQuest.java` to point to `src/main/resources/json/quests.json` instead of just `resources/json/quests.json`. Imported maven project into IntelliJ with default settings so maybe a misconfiguration on my part.

Total level calc treats invention as being on the regular xp curve so it's displaying me as 4 levels higher than I am.

Mournings End Part 1 & 2 are displaying as quests I should do, despite having done them a long time ago. It's also suggesting I do MEP2 before MEP1 which is odd.

Aside from that it's great :) Will close this issue now as it was originally opened for the combat only.

**Comment by darrenswhite** [comment]
I've fixed the elite xp table now. Also just updated pom.xml to include dependencies. I'll look into MEP1/2 now. It seems RuneMetrics uses slightly different naming for them.

**Comment by darrenswhite** [comment]
Fixed MEP1/2 names.
