### ISSUE TITLE
Some quests not registering as completed

### ISSUE THREAD

**Issue by Nowbob** [darrenswhite/ironquest#16]
Some quests show up in my queue even though they are completed, the examples right now are Dig Site, and the Fairy Tale series. I suspect it's a naming error. For example, IronQuest says "Dig Site" but the actual quest name is "The Dig Site". The same is true for all the Fairy Tale quests, they should all have "A Fairy Tale..." but IronQuest just has "Fairy Tale..."
I'm sure there are others, these are just what is sitting at the top for me that I notice.

**Comment by Nowbob** [comment]
In the case that naming is indeed the problem, I wrote a quick python script to pull names straight from runemetrics and compared against the quests.json in IronQuest. The following are the non-matches that runemetrics had that weren't found in quests.json:
(I pulled all the miniquest ones out, I'm not entirely familiar with the "saga" quests as well as some others in here, but I left the list mostly intact just in case)

A Fairy Tale I - Growing Pains
A Fairy Tale II - Cure a Queen
A Fairy Tale III - Battle at Ork's Rift
Elemental Workshop I
Garden of Tranquillity
The Dig Site
The Fremennik Isles
The Prisoner of Glouphrie
As a First Resort
Chef's Assistant
Curse of the Black Stone
Elemental Workshop II
Elemental Workshop III
Elemental Workshop IV
Fur 'n Seek
Kindred Spirits
Nadir (saga)
Recipe for Disaster: Another Cook's Quest
Recipe for Disaster: Defeating the Culinaromancer
Recipe for Disaster: Freeing Evil Dave
Recipe for Disaster: Freeing King Awowogei
Recipe for Disaster: Freeing Pirate Pete
Recipe for Disaster: Freeing Sir Amik Varze
Recipe for Disaster: Freeing Skrach Uglogwee
Recipe for Disaster: Freeing the Goblin Generals
Recipe for Disaster: Freeing the Lumbridge Sage
Recipe for Disaster: Freeing the Mountain Dwarf
Rum Deal
The Chosen Commander
The Curse of Arrav
The Great Brain Robbery
The Needle Skips
The Slug Menace
The Tale of the Muspah
Thok It To 'Em (saga)
Thok Your Block Off (saga)
Three's Company (saga)
Vengeance (saga)
Violet is Blue
Watchtower
You Are It

**Comment by kadem2** [comment]
Is this being worked on still? I'm having this problem with several quests.

**Comment by darrenswhite** [comment]
@kadem2 this has been fixed - I'll release the new version.

**Comment by kadem2** [comment]
Beautiful! Thanks for the quick reply/update! Love the tool :)
