### ISSUE TITLE
Wolf whistle showing up long after completion

### ISSUE THREAD

**Issue by marcucciboy2** [darrenswhite/ironquest#37]
I completed the quest long ago (even have 99 summoning) but it lists Wolf Whistle as incomplete for me.

RSN Donni Iris

**Comment by darrenswhite** [comment]
Hi @marcucciboy2. According to RuneMetrics (https://apps.runescape.com/runemetrics/app/quests/player/Donni+Iris) you haven't completed Wolf Whistle. IronQuest retrieves quest data from RuneMetrics. This means it's likely an issue with RuneMetrics.
