### ISSUE TITLE
Wrong order of quest's & xp lamp order

### ISSUE THREAD

**Issue by Rienokitsune** [darrenswhite/IronQuest#4]
After running program for my ironman i've noticed that some quest's are placed higher than quest's that are required to do that quest, for example river of blood is placed on first place but i haven't done any quest's of vampyre questline. there are much more quests like that ( appearing before their reqs )
the other issue is that some of the recommended xp lamp placements doesn't make much sense. 
for example my hunter lvl is 76 which is req for lord of vampyrium and is highest hunter quest req but i still see quest's with lamps that can be put in any skill and are recommending me to use it on hunter xD
screens below :)
![image](https://cloud.githubusercontent.com/assets/28676533/26028420/3b458d60-3820-11e7-95bf-0027a0e3efa1.png)

**Comment by darrenswhite** [comment]
Yes I believe this is similar to https://github.com/darrenswhite/IronQuest/issues/3 . I've pushed up a quick fix to v1.0.1 - if you could download it again and try again that would be great. Thanks.

**Comment by Rienokitsune** [comment]
Everything looks fine now :)
