### ISSUE TITLE
Incorrect reward for Meeting History quest

### ISSUE THREAD

**Issue by MisterBored** [darrenswhite/IronQuest#5]
![image](https://cloud.githubusercontent.com/assets/28933326/26420612/14488f90-4091-11e7-91df-a774b8a607fa.png)
The tool incorrectly states the rewards for the quest as being three 2.5k exp lamps
The correct reward is two 1k exp lamps and one 500 exp lamp
![image](https://cloud.githubusercontent.com/assets/28933326/26420695/5e62d3ec-4091-11e7-9088-25add95852a7.png)

**Comment by darrenswhite** [comment]
Fixed in https://github.com/darrenswhite/IronQuest/pull/6
