### ISSUE TITLE
Deadliest Catch requirements wrong

### ISSUE THREAD

**Issue by explorer-source** [darrenswhite/ironquest#67]
![image](https://github.com/darrenswhite/ironquest/assets/62930251/afec9ecf-21a7-4f06-b4f8-7a38b5e552ac)

I have 68 fishing yet its saying start with [Deadliest Catch](https://runescape.wiki/w/Deadliest_Catch) quest which requires you to have 70 fishing to start the quest

**Comment by darrenswhite** [comment]
Fixed by 67e1b9183b95b54e15088bb0e5657589dd2d1713
